#!/usr/bin/env bash
set -o errexit
set -o nounset

curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCILINT_VERSION}

# make reports directory (if it doesn't exist)
mkdir -p ${REPORTS_DIR}

echo "Running golangci-lint"
golangci-lint run ./...
echo "no linting problems found"
